/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCommitPatternsRouteImport } from './routes/dashboard/commit-patterns'
import { Route as DashboardHeatmapRouteImport } from './routes/dashboard/heatmap'
import { Route as DashboardLanguagesRouteImport } from './routes/dashboard/languages'
import { Route as DashboardPrsRouteImport } from './routes/dashboard/prs'
import { Route as DashboardReposRouteImport } from './routes/dashboard/repos'
import { Route as UUsernameRouteRouteImport } from './routes/u/$username/route'
import { Route as UUsernameIndexRouteImport } from './routes/u/$username/index'
import { Route as UUsernameCommitPatternsRouteImport } from './routes/u/$username/commit-patterns'
import { Route as UUsernameHeatmapRouteImport } from './routes/u/$username/heatmap'
import { Route as UUsernameLanguagesRouteImport } from './routes/u/$username/languages'
import { Route as UUsernamePrsRouteImport } from './routes/u/$username/prs'
import { Route as UUsernameReposRouteImport } from './routes/u/$username/repos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCommitPatternsRoute = DashboardCommitPatternsRouteImport.update({
  id: '/commit-patterns',
  path: '/commit-patterns',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHeatmapRoute = DashboardHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLanguagesRoute = DashboardLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPrsRoute = DashboardPrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReposRoute = DashboardReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const UUsernameRouteRoute = UUsernameRouteRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameIndexRoute = UUsernameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameCommitPatternsRoute = UUsernameCommitPatternsRouteImport.update({
  id: '/commit-patterns',
  path: '/commit-patterns',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameHeatmapRoute = UUsernameHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameLanguagesRoute = UUsernameLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernamePrsRoute = UUsernamePrsRouteImport.update({
  id: '/prs',
  path: '/prs',
  getParentRoute: () => UUsernameRouteRoute,
} as any)
const UUsernameReposRoute = UUsernameReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => UUsernameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/u/$username': typeof UUsernameRouteRouteWithChildren
  '/dashboard/commit-patterns': typeof DashboardCommitPatternsRoute
  '/dashboard/heatmap': typeof DashboardHeatmapRoute
  '/dashboard/languages': typeof DashboardLanguagesRoute
  '/dashboard/prs': typeof DashboardPrsRoute
  '/dashboard/repos': typeof DashboardReposRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/u/$username/commit-patterns': typeof UUsernameCommitPatternsRoute
  '/u/$username/heatmap': typeof UUsernameHeatmapRoute
  '/u/$username/languages': typeof UUsernameLanguagesRoute
  '/u/$username/prs': typeof UUsernamePrsRoute
  '/u/$username/repos': typeof UUsernameReposRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/commit-patterns': typeof DashboardCommitPatternsRoute
  '/dashboard/heatmap': typeof DashboardHeatmapRoute
  '/dashboard/languages': typeof DashboardLanguagesRoute
  '/dashboard/prs': typeof DashboardPrsRoute
  '/dashboard/repos': typeof DashboardReposRoute
  '/dashboard': typeof DashboardIndexRoute
  '/u/$username/commit-patterns': typeof UUsernameCommitPatternsRoute
  '/u/$username/heatmap': typeof UUsernameHeatmapRoute
  '/u/$username/languages': typeof UUsernameLanguagesRoute
  '/u/$username/prs': typeof UUsernamePrsRoute
  '/u/$username/repos': typeof UUsernameReposRoute
  '/u/$username': typeof UUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/u/$username': typeof UUsernameRouteRouteWithChildren
  '/dashboard/commit-patterns': typeof DashboardCommitPatternsRoute
  '/dashboard/heatmap': typeof DashboardHeatmapRoute
  '/dashboard/languages': typeof DashboardLanguagesRoute
  '/dashboard/prs': typeof DashboardPrsRoute
  '/dashboard/repos': typeof DashboardReposRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/u/$username/commit-patterns': typeof UUsernameCommitPatternsRoute
  '/u/$username/heatmap': typeof UUsernameHeatmapRoute
  '/u/$username/languages': typeof UUsernameLanguagesRoute
  '/u/$username/prs': typeof UUsernamePrsRoute
  '/u/$username/repos': typeof UUsernameReposRoute
  '/u/$username/': typeof UUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/u/$username'
    | '/dashboard/commit-patterns'
    | '/dashboard/heatmap'
    | '/dashboard/languages'
    | '/dashboard/prs'
    | '/dashboard/repos'
    | '/dashboard/'
    | '/u/$username/commit-patterns'
    | '/u/$username/heatmap'
    | '/u/$username/languages'
    | '/u/$username/prs'
    | '/u/$username/repos'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/commit-patterns'
    | '/dashboard/heatmap'
    | '/dashboard/languages'
    | '/dashboard/prs'
    | '/dashboard/repos'
    | '/dashboard'
    | '/u/$username/commit-patterns'
    | '/u/$username/heatmap'
    | '/u/$username/languages'
    | '/u/$username/prs'
    | '/u/$username/repos'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/u/$username'
    | '/dashboard/commit-patterns'
    | '/dashboard/heatmap'
    | '/dashboard/languages'
    | '/dashboard/prs'
    | '/dashboard/repos'
    | '/dashboard/'
    | '/u/$username/commit-patterns'
    | '/u/$username/heatmap'
    | '/u/$username/languages'
    | '/u/$username/prs'
    | '/u/$username/repos'
    | '/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  UUsernameRouteRoute: typeof UUsernameRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/commit-patterns': {
      id: '/dashboard/commit-patterns'
      path: '/commit-patterns'
      fullPath: '/dashboard/commit-patterns'
      preLoaderRoute: typeof DashboardCommitPatternsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/heatmap': {
      id: '/dashboard/heatmap'
      path: '/heatmap'
      fullPath: '/dashboard/heatmap'
      preLoaderRoute: typeof DashboardHeatmapRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/languages': {
      id: '/dashboard/languages'
      path: '/languages'
      fullPath: '/dashboard/languages'
      preLoaderRoute: typeof DashboardLanguagesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/prs': {
      id: '/dashboard/prs'
      path: '/prs'
      fullPath: '/dashboard/prs'
      preLoaderRoute: typeof DashboardPrsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/repos': {
      id: '/dashboard/repos'
      path: '/repos'
      fullPath: '/dashboard/repos'
      preLoaderRoute: typeof DashboardReposRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username/': {
      id: '/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof UUsernameIndexRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/commit-patterns': {
      id: '/u/$username/commit-patterns'
      path: '/commit-patterns'
      fullPath: '/u/$username/commit-patterns'
      preLoaderRoute: typeof UUsernameCommitPatternsRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/heatmap': {
      id: '/u/$username/heatmap'
      path: '/heatmap'
      fullPath: '/u/$username/heatmap'
      preLoaderRoute: typeof UUsernameHeatmapRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/languages': {
      id: '/u/$username/languages'
      path: '/languages'
      fullPath: '/u/$username/languages'
      preLoaderRoute: typeof UUsernameLanguagesRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/prs': {
      id: '/u/$username/prs'
      path: '/prs'
      fullPath: '/u/$username/prs'
      preLoaderRoute: typeof UUsernamePrsRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
    '/u/$username/repos': {
      id: '/u/$username/repos'
      path: '/repos'
      fullPath: '/u/$username/repos'
      preLoaderRoute: typeof UUsernameReposRouteImport
      parentRoute: typeof UUsernameRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardCommitPatternsRoute: typeof DashboardCommitPatternsRoute
  DashboardHeatmapRoute: typeof DashboardHeatmapRoute
  DashboardLanguagesRoute: typeof DashboardLanguagesRoute
  DashboardPrsRoute: typeof DashboardPrsRoute
  DashboardReposRoute: typeof DashboardReposRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCommitPatternsRoute: DashboardCommitPatternsRoute,
  DashboardHeatmapRoute: DashboardHeatmapRoute,
  DashboardLanguagesRoute: DashboardLanguagesRoute,
  DashboardPrsRoute: DashboardPrsRoute,
  DashboardReposRoute: DashboardReposRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface UUsernameRouteRouteChildren {
  UUsernameCommitPatternsRoute: typeof UUsernameCommitPatternsRoute
  UUsernameHeatmapRoute: typeof UUsernameHeatmapRoute
  UUsernameLanguagesRoute: typeof UUsernameLanguagesRoute
  UUsernamePrsRoute: typeof UUsernamePrsRoute
  UUsernameReposRoute: typeof UUsernameReposRoute
  UUsernameIndexRoute: typeof UUsernameIndexRoute
}

const UUsernameRouteRouteChildren: UUsernameRouteRouteChildren = {
  UUsernameCommitPatternsRoute: UUsernameCommitPatternsRoute,
  UUsernameHeatmapRoute: UUsernameHeatmapRoute,
  UUsernameLanguagesRoute: UUsernameLanguagesRoute,
  UUsernamePrsRoute: UUsernamePrsRoute,
  UUsernameReposRoute: UUsernameReposRoute,
  UUsernameIndexRoute: UUsernameIndexRoute,
}

const UUsernameRouteRouteWithChildren = UUsernameRouteRoute._addFileChildren(
  UUsernameRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  UUsernameRouteRoute: UUsernameRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
